package zx.soft.utils.springboot.domain;

import java.util.Date;

import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.springframework.data.domain.Persistable;

/**
 * An entity User composed by three fields (id, email, name).
 * The Entity annotation indicates that this class is a JPA entity.
 * The Table annotation specifies the name for the table in the db.
 */
@Entity
@Table(name = "users")
public class User implements Persistable<Long> {

	// An autogenerated unique id for each user
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long id;

	@NotNull
	private String email;

	@NotNull
	@Embedded
	private Name name;

	@NotNull
	private Date updateTime;

	public User() {
	}

	public User(long id) {
		this.id = id;
	}

	public User(String email, Name name, Date upDate) {
		this.email = email;
		this.name = name;
		this.updateTime = upDate;
	}

	@Override
	public String toString() {
		return "User:[id:" + id + ",name:" + name + ",email:" + email + ",update_time:" + updateTime + "]";
	}

	@Override
	public Long getId() {
		return id;
	}

	public void setId(long value) {
		this.id = value;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String value) {
		this.email = value;
	}

	public Name getName() {
		return name;
	}

	public void setName(Name name) {
		this.name = name;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Override
	public boolean isNew() {
		return true;
	}

	public static class Name {
		private String firstName;
		private String lastName;

		public Name() {

		}

		public Name(String firstName, String lastName) {
			this.firstName = firstName;
			this.lastName = lastName;
		}

		@Override
		public String toString() {
			return firstName + " " + lastName;
		}
	}

}