package zx.soft.utils.springboot.domain;

import java.util.Date;

import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * An entity User composed by three fields (id, email, name).
 * The Entity annotation indicates that this class is a JPA entity.
 * The Table annotation specifies the name for the table in the db.
 */

/**
 * Repository.save() is a dual purposed method for Insert as well as Update
 * There are two mechanisms used by Spring to decide if it must use Insert or Update on an entity:
 * By default, Spring inspects the Id-Property (@Id) of the entity, to figure out if the entity is new or not. If the identifier property is null, then the entity is treated as new, else not new.
 * Another way to take better control of this is by implementing Persistable. For entities that implement Persistable, Spring will call isNew(…) method to figure out if it must be Inserted or Updated.
 * link: http://stackoverflow.com/questions/28424444/how-spring-data-jpa-repository-save-only-do-update
 * @author donglei
 *
 */

@Entity
@Table(name = "users")
public class User {

	// An autogenerated unique id for each user
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long id;

	@NotNull
	private String email;

	@NotNull
	@Embedded
	private Name name;

	@NotNull
	private Date updateTime;

	public User() {
	}

	public User(long id) {
		this.id = id;
	}

	public User(String email, Name name, Date upDate) {
		this.email = email;
		this.name = name;
		this.updateTime = upDate;
	}

	@Override
	public String toString() {
		return "User:[id:" + id + ",name:" + name + ",email:" + email + ",update_time:" + updateTime + "]";
	}

	public void setId(long value) {
		this.id = value;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String value) {
		this.email = value;
	}

	public Name getName() {
		return name;
	}

	public void setName(Name name) {
		this.name = name;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public long getId() {
		return id;
	}

	public static class Name {
		private String firstName;
		private String lastName;

		public Name() {

		}

		public Name(String firstName, String lastName) {
			this.firstName = firstName;
			this.lastName = lastName;
		}

		@Override
		public String toString() {
			return firstName + " " + lastName;
		}
	}

}